language: node_js

node_js:
  - lts/*

os: linux

cache: yarn

install: yarn --frozen-lockfile

branches:
  only:
    - main

services:
  - postgresql
  - redis-server

before_script:
  - psql -c 'create database test_db;' -U postgres

script:
  - yarn test
