version: '3.7'
services:
  project_rest_api_dev:
    container_name: project_rest_api_dev
    restart: always
    build: .
    command: 'yarn dev'
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - project_network
    env_file:
      - .env
    depends_on:
      - project_db_postgresql
      - project_redis

  project_db_postgresql:
    container_name: project_db_postgresql
    image: 'postgres'
    restart: always
    ports:
      - 35432:5432
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./setup-postgresql.sh:/docker-entrypoint-initdb.d/setup-db.sh
      - project_db_data:/var/lib/postgresql/data/
    networks:
      - project_network

  project_redis:
    container_name: project_redis
    image: 'redis'
    restart: always
    ports:
      - 6379:6379
    volumes:
      - project_redis_data:/var/lib/redis
      - project_redis_data:/usr/local/etc/redis/redis.conf
    networks:
      - project_network

volumes:
  project_db_data:
    name: project_db_data
  project_redis_data:
    name: project_redis_data

networks:
  project_network:
    name: project_network
